export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR";

export const FETCH_WEATHER_HOURLY_START = "FETCH_WEATHER_HOURLY_START";
export const FETCH_WEATHER_HOURLY_SUCCESS = "FETCH_WEATHER_HOURLY_SUCCESS";
export const FETCH_WEATHER_HOURLY_ERROR = "FETCH_WEATHER_HOURLY_ERROR";

export const FILTER_HOURLY_WEATHER = "FILTER_HOURLY_WEATHER";

export const FETCH_WEATHER_WEEKLY_START = "FETCH_WEATHER_WEEKLY_START";
export const FETCH_WEATHER_WEEKLY_SUCCESS = "FETCH_WEATHER_WEEKLY_SUCCESS";
export const FETCH_WEATHER_WEEKLY_ERROR = "FETCH_WEATHER_WEEKLY_ERROR";

export const FETCH_CITY_START = "FETCH_CITY_START";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_ERROR = "FETCH_CITY_ERROR";
